// src/8-conditional/svelte/App.svelte
<script lang="ts">
    let counter = 0;

    const onClickHandler = () => {
        counter += 1;
    }

    $: isEven = !!(counter % 2);
</script>

<div>
    <p>{counter} is <!-- { isEven ? 'even' : 'odd' } -->
        {#if isEven}
            even
        {:else}
            odd
        {/if}
    </p>
    <button on:click={onClickHandler}>Click!</button>
</div>

// src/6-events/react/App.tsx
import React, { ReactElement, useState } from 'react';

export const App = (): ReactElement => {
    const [counter, setCounter] = useState(0);

    const onClickHandler = () => {
        setCounter(counter + 1);
    }

    return <div>
        <p>Clicks: {counter}</p>
        <button onClick={onClickHandler}>Click!</button>
    </div>;
}
