// src/14-appState/react/App.tsx
import React, { ReactElement } from 'react';
import { CalcContextProvider } from "./Context";
import { Screen } from "./Screen";
import { Add } from "./Add";
import { Remove } from "./Remove";
import { Reset } from "./Reset";

const columnStyles: React.CSSProperties = {
    display: 'flex',
    flexDirection: 'column',
}

const buttonsStyles: React.CSSProperties = {
    marginTop: '16px',
}

export const App = (): ReactElement => {
    return <CalcContextProvider>
        <div style={columnStyles}>
            <div>
                <Screen />
            </div>
            <div style={buttonsStyles}>
                <Add />
                <Remove />
                <Reset />
            </div>
        </div>
    </CalcContextProvider>
}

// src/14-appState/svelte/App.svelte
<script>
    import Screen from "./Screen.svelte";
    import Add from "./Add.svelte";
    import Remove from "./Remove.svelte";
    import Reset from "./Reset.svelte";
</script>

<style>
    .column {
        display: flex;
        flex-direction: column;
    }

    .buttons {
        margin-top: 16px;
    }
</style>

<div class="column">
    <div>
        <Screen />
    </div>
    <div class="buttons">
        <Add />
        <Remove />
        <Reset />
    </div>
</div>
