// src/12-componentEvents/svelte/Button.svelte
<script lang="ts">
    import { createEventDispatcher } from "svelte";

    export let buttonId;

    const dispatch = createEventDispatcher();

    const clickHandler = () => {
        dispatch('clicked', {
            buttonId
        });
    }
</script>

<button on:click={clickHandler}>Button {buttonId}</button>

// src/12-componentEvents/react/Button.tsx
import React, { MouseEventHandler, ReactElement } from 'react';

interface Props {
    buttonId: number;
    onClick: (buttonId: number) => void;
}

export const Button = ({buttonId, onClick}: Props): ReactElement => {
    const clickHandler: MouseEventHandler = (e) => {
        onClick(buttonId);
    }

    return <button onClick={clickHandler}>Button {buttonId}</button>;
}
