// src/7-computed/react/App.tsx
import React, { ReactElement, useEffect, useState} from 'react';

export const App = (): ReactElement => {
    const [counter, setCounter] = useState(0);
    const [evenOrOddText, setEvenOrOddText] = useState<'even' | 'odd'>('even');

    const onClickHandler = () => {
        setCounter(counter + 1);
    }

    useEffect(() => {
        setEvenOrOddText(counter % 2 ? 'odd' : 'even');
    }, [counter]);

    useEffect(() => {
        console.log('[React]');
        console.log(`${counter} is even or odd?: ${evenOrOddText}`);
    }, [counter, evenOrOddText]);


    return <div>
        <p>{counter} is {evenOrOddText}</p>
        <button onClick={onClickHandler}>Click!</button>
    </div>;
}

// src/7-computed/svelte/App.svelte
<script lang="ts">
    let counter = 0;

    const onClickHandler = () => {
        counter += 1;
    }

    $: evenOrOddText = counter % 2 ? 'odd' : 'even';

    $: {
        console.log('[Svelte]');
        console.log(`${counter} is even or odd?: ${evenOrOddText}`);
    }
</script>

<div>
    <p>{counter} is {evenOrOddText}</p>
    <button on:click={onClickHandler}>Click!</button>
</div>
